// <auto-generated />
using System;
using AppBolo2.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppBolo2.Migrations
{
    [DbContext(typeof(AppBoloContexto))]
    [Migration("20201112224630_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppBolo2.Models.Bolo", b =>
                {
                    b.Property<int>("IdBolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DiamentroCentimetro")
                        .HasColumnType("real");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeAndar")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeBolo")
                        .HasColumnType("int");

                    b.Property<string>("SaborMassa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaborRecheio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemaIdTema")
                        .HasColumnType("int");

                    b.Property<string>("TipoCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValorUnitario")
                        .HasColumnType("real");

                    b.HasKey("IdBolo");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TemaIdTema");

                    b.ToTable("Bolo");
                });

            modelBuilder.Entity("AppBolo2.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataPagamento")
                        .HasColumnType("int");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPagamento");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("AppBolo2.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataPedido")
                        .HasColumnType("int");

                    b.Property<int?>("PagamentoIdPagamento")
                        .HasColumnType("int");

                    b.Property<string>("StatusPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoIdPagamento");

                    b.HasIndex("UserId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("AppBolo2.Models.Tema", b =>
                {
                    b.Property<int>("IdTema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Personalizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predefinido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTema");

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("AppBolo2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CPF")
                        .HasColumnType("real");

                    b.Property<float>("CartaoCredito")
                        .HasColumnType("real");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Telefone")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("AppBolo2.Models.Bolo", b =>
                {
                    b.HasOne("AppBolo2.Models.Pedido", null)
                        .WithMany("Bolo")
                        .HasForeignKey("PedidoId");

                    b.HasOne("AppBolo2.Models.Tema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaIdTema");
                });

            modelBuilder.Entity("AppBolo2.Models.Pedido", b =>
                {
                    b.HasOne("AppBolo2.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoIdPagamento");

                    b.HasOne("AppBolo2.Models.User", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
